scripts:
  - name: "http_ngsild_proxy.py"
    path: "/mini-ndn/app/ngsild_dir/"
    log: "http_ngsild_proxy_logs.log"
    log_path: "/mini-ndn/app/logs/"
    environment_variables:
      - '--host-ip'
      - '0.0.0.0'
      - '--server-port'
      - '8080'
      - '&'  # background service
    run_from_main: True

  - name: "SNDS_r_service.py"
    path: "/mini-ndn/app/producer_dir/"
    log: "SNDS_r_service_logs.log"
    log_path: "/mini-ndn/app/logs/"
    environment_variables:
      - '--r-type'
      - 'car'
      - '--host-name'
      - 'producer'
      - '&'  # background service
    run_from_main: True

  - name: "SNDS_service.py"
    path: "/mini-ndn/app/consumer_dir/"
    log: "SNDS_service_logs.log"
    log_path: "/mini-ndn/app/logs/"
    environment_variables:
      - '--host-name'
      - 'consumer'
      - '--object'
      - 'item1'
      - '--r-type'
      - 'car'
    run_from_main: False

  - name: "closestCDNNode_byType.py"
    path: "/mini-ndn/app/ngsild_dir/"
    # shares file with proxy
    log: ""
    log_path: ""
    # inputted dynamically inside http proxy
    environment_variables: []
    run_from_main: False

  - name: "closestCDNNode_byID.py"
    path: "/mini-ndn/app/ngsild_dir/"
    # shares file with proxy
    log: ""
    log_path: ""
    # inputted dynamically inside http proxy
    environment_variables: []
    run_from_main: False
