version: '3.8'

services:
  producer:
    build: ${PRODUCER_BUILD_CONTEXT}
    mem_limit: 4g
    cpus: 4
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
    command: > 
        python3 SNDS_r_service.py 

  consumer:
    build: ${CONSUMER_BUILD_CONTEXT}
    mem_limit: 4g
    cpus: 4
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
    command: >
        python3 SNDS_service.py

  ngsild:
    build: ${NGSILD_BUILD_CONTEXT}
    mem_limit: 4g
    cpus: 4
    privileged: true
    ports: 
        - "${NGSILD_PORT}:8080"
    volumes:
      - /lib/modules:/lib/modules
    environment: 
        - HOSTNAME=${NGSILD_HOSTNAME}
        - PORT=${NGSILD_PORT}
    command: > 
        python3 http_ngsild_proxy.py

  snds: 
    build: ${SNDS_BUILD_CONTEXT}
    mem_limit: 4g
    cpus: 4
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
    command: > 
        python3 snds.py snds-topology.conf
    
