version: '3.8'

services:
  snds: 
    build: ${SNDS_BUILD_CONTEXT}
    mem_limit: 4g
    privileged: true
    environment: 
      - HTTP_PROXY_HOSTNAME=${HTTP_PROXY_HOSTNAME}
      - HTTP_PROXY_PORT=${HTTP_PROXY_PORT}
      - PRODUCER_HOSTNAME=${PRODUCER_HOSTNAME}
      - FORWARDER_HOSTNAME=${FORWARDER_HOSTNAME}
      - CONSUMER_HOSTNAME=${CONSUMER_HOSTNAME}
      - CLOSEST_HOSTNAME=${CLOSEST_HOSTNAME}
      - NGSILD_HOSTNAME=${NGSILD_HOSTNAME}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - /lib/modules:/lib/modules
    command: > 
        python3 snds.py snds-topology.conf
    
