version: '3.8'

services:
  producer:
    image: ghcr.io/named-data/mini-ndn:master
    mem_limit: 4g
    cpus: 4
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
    command: > 
        python3 SNDS_r_service.py 

  consumer:
    image: ghcr.io/named-data/mini-ndn:master
    mem_limit: 4g
    cpus: 4
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
    command: >
        python3 SNDS_service.py

  ngsild:
    image: ghcr.io/named-data/mini-ndn:master
    mem_limit: 4g
    cpus: 4
    privileged: true
    ports: 
        - "8080:8080"
    volumes:
      - /lib/modules:/lib/modules
    environment: 
        - HOSTNAME=10.0.0.13
        - PORT=8080
    command: > 
        python3 http_ngsild_proxy.py

