scripts:
  - name: "http_ngsild_proxy.py"
    path: "/app/snds/ngsild_dir/"
    log: "http_ngsild_proxy_logs.log"
    log_path: "/app/snds/logs/"
    environment_variables:
      - '--host-ip'
      - '0.0.0.0'
      - '--server-port'
      - '8080'
    background_service: True
    run_from_main: True

  - name: "SNDS_r_service.py"
    path: "/app/snds/producer_dir/"
    log: "SNDS_r_service_logs.log"
    log_path: "/app/snds/logs/"
    environment_variables:
      - '--r-type'
      - 'car'
    background_service: True
    run_from_main: True

  - name: "SNDS_service.py"
    path: "/app/snds/forwarder_dir/"
    log: "SNDS_service_logs.log"
    log_path: "/app/snds/logs/"
    environment_variables: []
    run_from_main: False

  - name: "closestCDNNode_byType.py"
    path: "/app/snds/ngsild_dir/"
    # shares file with proxy
    log: "closestCDNNODE_byType.log"
    log_path: "/app/snds/logs/"
    # inputted dynamically inside http proxy
    environment_variables: []
    background_service: False
    run_from_main: False

  - name: "closestCDNNode_byID.py"
    path: "/app/snds/ngsild_dir/"
    # shares file with proxy
    log: "closestCDNNode_byID.log"
    log_path: "/app/snds/logs"
    # inputted dynamically inside http proxy
    environment_variables: []
    background_service: False
    run_from_main: False
